<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Robô da Alegria :: API</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Robô da Alegria</h1>
        <div>API de desenvolvimento com simulação dos movimentos do robô</div>

        <?php if (isset($data)) : ?>
            <p>Comando recebido <?= htmlspecialchars($data['param']."=".$data['command']); ?></p>
            <img src="assets/images/<?php echo $data['param'].$data['command']; ?>.png" style="width:100px">
        <?php else: ?>
            <p>Nenhum comando válido recebido. Consulte <a href='<?php echo "http://".$request->getServerParams()['HTTP_HOST']; ?>'>aqui</a> a lista de comandos válidos 
        <?php endif; ?>

        <p><a href='<?php echo "http://".$request->getServerParams()['HTTP_HOST']; ?>'>Voltar a lista de comandos</a></p>
    </body>
</html>
